### ISSUE TITLE
Windows Platform: UTF-8 problems on console writings

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#101]
Like bug #99 Windows is very bad in terms of modern standards ... It seems any writings on the console window has strange result if non-US-ASCII characters included. Even if I tried to enable some "magic code page" means UTF-8 by some resources, I'm not sure ... This was the one:

    SetConsoleOutputCP(65001); // CP_UTF8

**Comment by hernandp** [comment]
Checked it out from current dev branch. I added the following test string in emutools.c:

``` 
DEBUGPRINT("WINDOWS: console is open CHARS: \u2500\u2501\u2502\u2503\u2504\u2505\u2506\u2507\u2508\u2509\u250A\u250B\u250C\u250D\u250E\u250F\n CHINESE: \u2eb4\u2eb5\u2eb6\u2eb7\u2eb8\u2eb9\u2eba\u2ebb\u2ebc\u2ebd\u2ebe\u2ebf\u2ec0\u2ec1\u2ec2\u2ec3\n" NL);
```

That will try to print box drawing characters and Chinese characters to the console. 

Let's see how it goes. 

**Consolas font (default for Windows 10)**

![image](https://user-images.githubusercontent.com/4740613/74501361-a95b9a80-4ec8-11ea-8c68-98047c7d3a14.png)

Drawing box characters OK but no support for Chinese.

**Lucida Console**
![image](https://user-images.githubusercontent.com/4740613/74501649-90071e00-4ec9-11ea-8638-57012e053167.png)


No support, BAD.

**MS Mincho bitmap font:**
![image](https://user-images.githubusercontent.com/4740613/74501444-ecb60900-4ec8-11ea-85ad-bfea8871090e.png)

Supports all ranges, displays OK.

**I think this is working properly**, if the correct font is selected. Default Windows is Consolas, so if you don't use out of range Unicode characters, console output should be good for most purposes.

For reference, here is what Unicode range Consolas supports: 
https://www.fileformat.info/info/unicode/font/consolas/grid.htm

**Comment by hernandp** [comment]
In my opinion, this can be put in the Xemu documentation or README, in a Windows specific section.

**Comment by lgblgblgb** [comment]
Hmm, I wouldn't think I need Chinese characters soon in Xemu :D I more meant to have eg my name. When I tested Xemu for Windows I used Wine in Linux. That's a minor concern really to have missing special Hungarian characters on the console from my name. That was more a problem that from that point, no any output was done (!!!) only after SEVERAL missing lines of output. But, if it's a wine specific thing only, and should work in general, I don't even mind if a given character is bad. The only ugly thing was truncate the whole output in wine after any non-US-ASCII char!

**Comment by hernandp** [comment]
Yes, the only warning for Windows users would be to select a proper font that could draw the standard Unicode character .  Fortunately, default in Windows > 7 is Consolas which works well.

**Comment by lgblgblgb** [comment]
Btw, have you seen the help menu point in the UI menu on newer Xemu's? It should launch a browser instance (or tab, whatever) it seems to work on Linux at least, and in Windows (whatever I could tested ...) no idea on Mac. The idea here, that including a large help material into Xemu's binary is a bit overkill especially since Xemu UI does not have any nice UI widget to display large text and easy navigation. Also using the web for that makes more sense for me, and more easy editing even without need to update Xemu for users to see changes of course. I mention this, because your comment about adding font suggestion into Xemu documentation reminded me. I guess about nobody do RTFM :) especially not the large amount of DOC mostly about technical stuff like compiling Xemu etc, simply too overloaded.  If you use the help function it leads you into the wiki section of xemu, currently that page has only one important link, which describes the preparation of the SD-card image (which is sane, as you CAN start Xemu/MEGA65 without SD-card emulation yet working, and then you can use the UI, so the user needs only know how to get the UI at all, to get more information).

**Comment by lgblgblgb** [comment]
I guess I close this then for now ...
