### ISSUE TITLE
Xemu: create, then donate an icon, integrate into Xemu

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#102]
Xemu should have an icon. I have no artistic talents AT ALL, you can't imagine how true this statement is. So it would be great if someone creates something nice, and "donating" it.

As the second part: it should be integrated into Xemu, so it sets as the SDL window icon at least, for starting point.

**Comment by hernandp** [comment]
![image](https://user-images.githubusercontent.com/4740613/72742138-dcd82d00-3b87-11ea-95fb-16e2b576e6d8.png)

What do you think?

**Comment by lgblgblgb** [comment]
It's nice for me :D If you agree to be licensed together with Xemu etc. Do you have bigger version too, I mean higher resolution? It would be cool to have some sizes, because it may be needed for various reasons (window icon as SDL level, exe-embeded one, Linux desktop icons ... whatever).

**Comment by hernandp** [comment]
Of course, I can provide several size and formats, no problem.

**Comment by lgblgblgb** [comment]
Nice :D So you can post it here, _OR_ for sure, you can "PR it" into the Xemu. Initially the method should be: ``build/xemu-32x28.xpm`` as you can see this is 32x28 pixel resolution XPM format. This is used here and there, but not everywhere (yet). I would suggest (if you prefer this, and not just send me - it's up to you!) to make a PR with replacing that file, with the 32x28 resolution (in fact the file name is important and I wouldn't like to have different resolution what the file name suggest, but that file is used, so the name is important, logic cycle here :) ). BUT. For sure it would be nice to have some different resolution one**s** in whatever format (preferably in PNG) in the same directory with different naming scheme (eg: ``build/xemu-48x48.png``.  Just that single X-pixmap (xpm) is important to have as it is now (resolution, file name). Later, we can think about using other resolutions, different formats, etc, that why, ideally there should be multiple resolutions ready to be used over the xpm still :)

Btw, the xpm format is also nice, since in fact it's a C program fragment. So it is very easy to just ``#include`` in Xemu and using that way to set as the window icon etc. Meanwhile, the build mechanism (eg, the DEB package, but the NSI installer stuff as well) convert it during "make-time" to other format and using that way.

OK, waaaay too long comment from me again, just I wanted to give some hints.

**Comment by lgblgblgb** [comment]
Initially now, I put your icon in, commit: a63a2bbd94a5c16a6b7b68fa7f3f5d5484f14b03

Maybe not ideal, 48x48 now, converted to ~64 colours (the xpm should be represented by one char / pixel!).

**Comment by hernandp** [comment]
I did enhancements to the design that I will propose later, thanks.   I think the builtin XPM should be 32x32, why did you use 32x28 in xpm file ?

**Comment by hernandp** [comment]
Thanks I have 256x256, 32x32 and 16x16 sizes also.
