### ISSUE TITLE
Allow pasting keystrokes from the OS clipboard

### ISSUE THREAD

**Issue by sausagejohnson** [lgblgblgb/xemu#103]
Allow copied content, like a line from a listing (User Guide code for example) to be pasted into the emulator using the right mouse button, and will simulate keystrokes.

**Comment by lgblgblgb** [comment]
Seems to be useful idea! I'm wondering how to do that, since the emulator cannot know, if the emulated machine is "ready" to accept a new char, especially if a large program in memory (BASIC) so it takes a lot after the ENTER to wait. Without this knowledge, some keys will be missed by the emulated machine, regardless Xemu gives that too.

I'm thinking how to solve it well, thanks for the feature request!

**Comment by lgblgblgb** [comment]
Btw, it's probably more easy to paste something directly to the BASIC memory, and not as keystrokes. And also much faster, especially in case of larger portion. However that's true: it's not the same, and it cannot be used too much to paste commands, not programs (no BASIC line number), or for using other purposes, like pasting text for a running program actually, and not to enter a program ...

**Comment by sausagejohnson** [comment]
Either way would be good. If it can go into BASIC directly, that would be much better. As long as there is some way to get code into Xemu without typing, it would be such a benefit, and would accelerate the effort to produce and document MEGA65 code.

**Comment by lgblgblgb** [comment]
I see. This is not trivial anyway. First, I would like to finish the _output_ of basic memory to text file and//or clipboard (and you know, the Tex ...) :) This is, you see, the opposite of this, but indeed, useful thing to have.

**Comment by lgblgblgb** [comment]
Maybe it should be done as a kind of Xemu core framework and allow to have its effect via the HID layer, so it would work with any emulator?

**Comment by lgblgblgb** [comment]
I know, it's not the same, but there is a new feature currently in the `next` branch in commit 6a053a50cbd0d739b5b1ad3eff4d90e695dc2981 which allows to paste clipboard to the screen memory at least. Surely, if it's a BASIC program, still it's needed to tap RETURN on the lines after that to be entered, but still easier than typing them in "by hand", and can be useful in relative short programs (fits onto the screen) or commands.

**Comment by lgblgblgb** [comment]
Note: #391 makes possible to implement a nicer paste functionality for emulated MEGA65 now! Closing this issue now in favor of that one.
