### ISSUE TITLE
Switching from MEGA65 mode to C64 mode

### ISSUE THREAD

**Issue by Edilbert** [lgblgblgb/xemu#134]
A sequence of 45GS02 instructions, which switch to C64 mode and 80 column screen work well on a real MEGA65, but fail in XEMU:

Version: CREATED: travis@lgb on Darwin 18.7.0 at Sat Jun 20 19:57:30 GMT 2020

Code (assembled with BSA (https://github.com/Edilbert/BSA))

`.CPU 45GS02

SCREEN         = $0800
Kernal_Restore = $fd15
Init_IO        = $fda3
Init_Editor    = $ff5b
CHROUT         = $ffd2

START = $2001   ; *** BASIC ***  C65

* = START

          .LOAD START
          .STORE START,EOP-START,"mwe"

; ************
; basic_header
; ************

          .WORD Link
          .WORD 2020      ; line number
          .BYTE $fe,$02   ; BANK token
          .BYTE "0:"      ; BANK argument
          .BYTE $9e       ; SYS  token
          .BYTE "(8211)",0; C65  start
Link      .WORD 0         ; BASIC end marker

; **********
  MEGA_Setup
; **********
          sei
          lda #0              ; Configure MEGA65 memory
          tax
          tay
          taz
          map
          eom

          lda #$36  ; I/O & kernal
          sta 1
          lda #65   ; 40 MHz
          sta 0

          jsr Init_IO
          jsr Kernal_Restore
          jsr Init_Editor
          jsr Set_Mode_80
          cli

          lda #'*'
          sta SCREEN
wait      jmp wait

; ***********
  Set_Mode_80
; ***********

;         make VIC IV registers visible

          lda #$47
          sta $d02f
          lda #$53
          sta $d02f

          LDA #$c0           ; 80 columns, fast
          STA $d031
          LDA #$26           ; SCR = $0800,  CB = $0C00
          STA $d018
          RTS

; ***
  EOP
; ***
`
Screen photo of a real MEGA65 after loading and running the code:
![P1050355](https://user-images.githubusercontent.com/6380947/89452614-3daf0780-d75e-11ea-94a5-f48dfefd87f4.JPG)

Screenshot of XEMU after loading and running the same program:
<img width="752" alt="Bildschirmfoto 2020-08-05 um 20 46 36" src="https://user-images.githubusercontent.com/6380947/89452727-6afbb580-d75e-11ea-9f7e-e649c18356b4.png">

**Comment by lgblgblgb** [comment]
Please make sure if the problem is the same in Hernan's fork, since he is about rewrite major part of the whole VIC-IV emulation. Thus, if you see the problem the same there, we can have some conclusion. Even if the problem is a bit different but still there. Also useful information if there is no problem in that fork. :) Since MEGA65 emulation in the Xemu project is very basic, no wonder there are MILLIONS of problem, that's why it would be important to see it's really the VIC emulation or something other.

**Comment by lgblgblgb** [comment]
One interesting thing, that if I replace your ROM calls to the one I used here: https://github.com/lgblgblgb/mega65-utils/blob/master/c65izer/c65izer.asm
then it seems to work. But again, this does not explain then why it works on MEGA65, I mean in the original form.

**Comment by Edilbert** [comment]
The issue is solved with:
LDA #4 
STA $0288 ; screen memory page
before calling the editor initialisation.
This location has after power on 4 on a MEGA65 and 0 in XEMU, which made the initialisation routine for XEMU believe,
that the screen memory started with the zero page with all fatal consequences.
