### ISSUE TITLE
MEGA65+C65: figure out how sprites are handled on C65 when bitplane mode is used

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#139]
As noted in bug #126 there is some problem with sprites when bitplane mode is used. Namely, it's unclear where the sprite pointers are. This may affect mega65-core itself as well, to be C65-correct.

Material for #142 so part of #92

**Comment by lgblgblgb** [comment]
K2 demo from Zed Yago illustrates the problem (see below). For now, it seems, in bitplane mode, the video matrix "tail" is used still for sprite pointers, but at least now it seems, always at the end of a 2K sized video matrix, not what would be logical based on H640 set or clear. Also, it's unclear that it's based on the current 16K VIC-II style bank, or the 32K VIC-III style bank. This probably needs some test program written and run a real C65 to be sure.

![k2](https://user-images.githubusercontent.com/884916/92106044-0f1b5f80-ede4-11ea-8110-bd5a45a1a781.png)

**Comment by lgblgblgb** [comment]
Material for #142

**Comment by lgblgblgb** [comment]
It would be nice to have this for #29 as well for THE MERGE ;)

**Comment by lgblgblgb** [comment]
I'm unsure about this. Is it clear where sprite pointers are by default (not after setting with the VIC-IV specific registers ...) in case of bitplane modes? It would an issue for me, but at least on MEGA65 it may has been already resolved as a part of project #29 .

@hernandp Do you have opinion on this topic?

**Comment by hernandp** [comment]
I have a bitplane application using BASIC65, can I do some tests over. What do you think?

**Comment by lgblgblgb** [comment]
> I have a bitplane application using BASIC65, I can do some tests over it. What do you think?

Would be great, I think. Probably ROM does it in the right way, so if you can get sprites using V400/V200 and H640/H320 and their combinations with sprites are shown meanwhile and it's correct in all cases, I guess then it should be OK. Though I am not sure if BASIC65 does not use VIC-IV trickery to set sprite pointers in "MEGA65 way" and maybe the legacy sprite pointer state can be still incorrect (maybe for that some original BASIC 10 tests should be used!).

**Comment by lgblgblgb** [comment]
I guess it's kinda of outdated, as the current state of the MEGA65 emulation "should be OK" and probably the sprite behaviour of MEGA65 is identical anyway to C65 in terms of using bit plane mode + sprite, what this issue is about. So I'm closing this now.

**Comment by lgblgblgb** [comment]
Though **NOTE**: it's kind of possible, that it's not OK on the C65 emulator, however that can be part of the "K2 demo" issue anyway.
