### ISSUE TITLE
MacOS Platform: Cannot compile "hmw" branch on MacOS Catalina

### ISSUE THREAD

**Issue by JesperGravgaard** [lgblgblgb/xemu#146]
**Describe the bug**

Compiling HMW branch on fresh install of macOS Catalina fails with an error.

**Used version of the project**
HMW branch (commit 61d87a5) with the fix to #144 already applied.

**To Reproduce**
1. Install MacOs Catalina 10.15.6
2. Install homebrew
3. brew update
4. brew install sdl2 wget git
5. git clone git@github.com:lgblgblgb/xemu.git
6. cd xemu
7. git checkout hmw
8. apply fix to #144
9. make

**Expected behavior**
Successful compile.

**Actual behavior**

The following error during compile:
```
cc -Wall -fno-common -std=gnu11 -pipe  -Ofast -ffast-math -falign-functions=16  -I/usr/local/include/SDL2 -D_THREAD_SAFE    -I. -I../.. -include build/configure/config-native.h -c -o ../../build/objs/t-native-mega65-xmega65--sdcontent.o sdcontent.c
sdcontent.c:461:2: error: implicit declaration of function 'mfat_flush_fat_cache' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        mfat_flush_fat_cache();
        ^
sdcontent.c:516:2: error: implicit declaration of function 'mfat_flush_fat_cache' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        mfat_flush_fat_cache();
        ^
sdcontent.c:648:3: error: implicit declaration of function 'mfat_flush_fat_cache' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                mfat_flush_fat_cache();
                ^
3 errors generated.
make[3]: *** [../../build/objs/t-native-mega65-xmega65--sdcontent.o] Error 1
make[2]: *** [do-all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 1

```

**Comment by lgblgblgb** [comment]
Thanks for the report. That's interesting, is this behaviour is MacOS version dependent? Since I have Travis integration to compile the project after every commits and even Mac builds fine, so the only thing I can think of, is the different behaviour of different MacOS versions (including C compiler etc too).

**Comment by lgblgblgb** [comment]
I've made a comment on the pull request.

**Comment by lgblgblgb** [comment]
I close this now, since hmw branch currently is totally realm of @hernandp and it seems he already handled this. Again, thanks for your time to help us.
