### ISSUE TITLE
UI: implement OSD UI

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#203]
Some Xemu ports would need a version of Xemu only using its single output rendering target for anything, also for menus, dialogs, etc!

Depends on issue #224 (re-work of OSD functionality in Xemu).

**Comment by SiirRandall** [comment]
Would something like Vice UI menu work in something like this. They use SDL1/2 and in framebuffer mode they have a menu that works ok. I know it's totally two different emulators going on, but it might be something to look at.

**Comment by lgblgblgb** [comment]
@SiirRandall Xemu already has an OSD subsystem, I plan to use as the OSD UI as well. If you press right-ALT and TAB (not the left-ALT!) you access the so called "matrix mode" (what a real MEGA65 has too, albeit - currently - they use quite different commands). So Xemu is able to use the emulator window with/without transparency and alpha blending on top of the emulated machine as console / text / menu / whatever. The good value of it, that it does not depend on other window, so it's totally independent of the SDL texture's (and renderer's) nature, being an X11 window, SDL on frame buffer or anything else, works the same way. The "only" work here is to built the actual UI based on the OSD API of Xemu, you see. Currently the major bottleneck is the immature input/event subsystem of Xemu, what is also needed for better keyboard and joystick support even for the emulation, thus that must be done by me first.

**Comment by lgblgblgb** [comment]
I close this for now and consider "ready". Yes, it's not perfect yet, missing the save functionality and some bugs here and there, but it's more or less "minor" works only and bug fixes, the scope of this issue was to implement it at all.
