### ISSUE TITLE
MEGA65: implement VIC-IV features correctly needed by YAPED32

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#212]
**The one which needs to be tested**: [ydist.zip](https://github.com/lgblgblgb/xemu/files/6618248/ydist.zip)

YAPED32 currently does not run in emulation, not even with the VIC-IV branch of @hernandp 
Since it would be important (IMHO) to have all pending issues at once place, before forgetting some of them, I transfer these problems here.

At the moment, YAPED32 uses

* `PALNTSC`     (`$D06F`, _bit 7_)
* `TBDRPOS`   (`$D048` / `$D049`)
* `BBDRPOS`   (`$D04A` / `$D04B`)
* `TEXTXPOS` (`$D04C` / `$D04D`)
* `TEXTYPOS` (`$D04E` / `$D04F`)

to reconfigure the VIC-IV to display 5 extra lines at the bottom of the screen for the colour and character palettes,

* `SPRPTR16` (`$D06E`, _bit 7_)
* `SPRPTRADR` (`$D06C`, `$D06D`)
* `SPRPTRBNK` (`$D06E`, _bits 6-0_)

to get the sprites out of the way in bank 0, and

* `HOTREG` (`$D05D`, _bit 7_)

to reset screen & sprite modes in case of errors.

The next features I had planned: Supporting super-extended character mode and a proper, interrupt driven mouse driver... but seeing as feedback & downloads are a little bit on the slow side (and BASIC10 really s*cks ;-)), it's not necessarily a priority right now...

The source of this issue, where I quoted the text from (**important**: there prg on the forum mentioned above is very old, it should not be used, but the one at the top here):

https://www.forum64.de/index.php?thread/107033-yaped32-a-32-colour-petscii-editor-for-the-mega65/&postID=1584413#post1584413

**Comment by hernandp** [comment]
Thanks for adding this my friend .  I'll tackle YAPED32 the next week to see how far I can get with the my VIC-IV code.

**Comment by lgblgblgb** [comment]
Nice :D I've introduced a new label as "compatibility example" when some given software has problems. It's important since usually development is "in the dark" ie implementing what "it should do" but sometimes nothing to test with for real ... So well defined examples are important. YAPED32 fits into this category. Also others, maybe more to come. Currently:

https://github.com/lgblgblgb/xemu/labels/compatibility%20example

**Comment by lgblgblgb** [comment]
Should be re-visited in `merger`.

**Comment by lgblgblgb** [comment]
Do we have anything to do/fix in `merger` for this one now? I have some faint memory about bad sprite position or such ... ?

**Comment by lgblgblgb** [comment]
I close this now. Existing possible issue should be addressed per-issue. But in general, YAPED32 now seems to work, the minor issue of sprite position: I have no idea, but it sounds like more a very specific problem rather than this all-about issue. So it seems bulk of the past problems has been resolved in general at least, with the VIC-IV improvements.

**Comment by lgblgblgb** [comment]
New related issue: #313
