### ISSUE TITLE
CORE: Help (online) menu, none of the help menu items works on Windows

### ISSUE THREAD

**Issue by mindrail** [lgblgblgb/xemu#217]
**Describe the bug**
All 4 menu items in the help menu just open a windows explorer.exe to "This PC" "Documents" default folder.
The expected behavior would be for a web browser to open to the menu item url (download the book, or the xemu download page, etc). 
This is on Windows 10.

**Used version of the project**
WINDOWS: console is open
INFO: Xemu/MEGA65 20201103005224
https://github.com/lgblgblgb/xemu.git HEAD 566ff32b43c417d570a5a177d8b976c286fbfe0a (official-build)
Compiled by: travis@lgb on Linux 5.4.0-1028-gcp at Tue 03 Nov 2020 12:44:12 AM UTC
Built with: gcc-mingw64 9.3-win32 20200320 64LE for win64

Copyright (C)2016-2020 Gábor Lénárt (aka LGB) lgb@lgb.hu
http://lgb.hu/
This software is part of the Xemu project:
https://github.com/lgblgblgb/xemu

**To Reproduce**
1. Right click the Xemu65 window
2. Left click Help (Online)
3. Left click any help menu option
4. Click Yes to "Can I open a web browser instance/window/tab to be able to serve your request?"
5. 
...

**Expected behavior**
The expected behavior would be for a web browser to open to the menu item url (download the book, or the xemu download page, etc). 

**Screenshots**

It opens this instead:

![image](https://user-images.githubusercontent.com/29457753/101278222-f74fdf00-3809-11eb-9ea6-3a40ba13a687.png)

**Computer/Device (please complete the following information):**
 - Device/Platform: PC
 - OS and its version: Windows 10 64bit 
 - Browser and its version - _if applies_: All.

**Additional context**

Here is the console dump:

BROWSER: requesting web resource to open: https://lgblgblgb.github.io/xemu/xemuonlinerequest.html?xemuonlinehelprequesttoken=o%3D1%01v%3D20201103005224%01b%3Dhttps%3A%2F%2Fgithub%2Ecom%2Flgblgblgb%2Fxemu%2Egit%20HEAD%20566ff32b43c417d570a5a177d8b976c286fbfe0a%01t%3Dmega65%01p%3Dwin64%01u%3D1607252126%01x%3Dhelp%02chk
EXEC: FILEBROWSER: previous file browser process (70099616) status was: 1
EXEC: ("explorer" https://lgblgblgb.github.io/xemu/xemuonlinerequest.html?xemuonlinehelprequesttoken=o%3D1%01v%3D20201103005224%01b%3Dhttps%3A%2F%2Fgithub%2Ecom%2Flgblgblgb%2Fxemu%2Egit%20HEAD%20566ff32b43c417d570a5a177d8b976c286fbfe0a%01t%3Dmega65%01p%3Dwin64%01u%3D1607252126%01x%3Dhelp%02chk) seems to be OK :-)

I did try to look around the code to see what the issue was, but my knowledge of the code was not good enough,

**Comment by lgblgblgb** [comment]
Yeah, windows is strange no idea how windows should work in this regard. I don't even have windows, only write/test Xemu/Windows by using Wine on Linux, not an actual Windows OS. I guess, Windows have some separate binary to be called for web URLs than file ones ... I'll try to "google it" how this should work on Windows. Thanks for the report! I don't think it's a code problem btw, more like not knowing (by me) how command line intended to be used in Windows to open a web browser window/tab.

**Comment by lgblgblgb** [comment]
https://superuser.com/questions/36728/can-i-launch-urls-from-command-line-in-windows

Hmm it seems Windows would need the "start" command not actually "explorer". That's strange since either on Mac and Linux, there is a common wrapper for both, it's not the same on Windows then it seems. Oh well, fair enough, I'll try that some time!

**Comment by lgblgblgb** [comment]
Argh, Windows is a nightmare, to need tricks for all normal things to do :( Anyway, hopefully now it works. So closing this issue.

**Comment by lgblgblgb** [comment]
Note: still it can be a problem to pass '&' character on Windows. However currently Xemu does not use that at all, thus it can't cause an issue.
