### ISSUE TITLE
MEGA65+C65: second F011 drive emulation

### ISSUE THREAD

**Issue by Edilbert** [lgblgblgb/xemu#219]
Could there be an option "-9" for mounting another image to device 9 ?
Then we could test programs, which use two units.
For example:
xmega65 -8 MEGA65.D81 -9 TOOLS.D81

**Comment by lgblgblgb** [comment]
The problem, that not just -9 missing but anything "behind the scenes" to deal at all with more than one D81s, especially with external source (ie, not from SD-card). However it may happen some time, just I cannot tell when ... Thanks for the report, it's important to collect all the needs.

**Comment by lgblgblgb** [comment]
# Plan (aka. note to future myself):

1. Modifying F011 emulation (used by both of C65 and MEGA65 emulation, `xemu/f011_core.c`) to have at least any emulation of more than one disk. It seems F011 controller provides the needed infrastructure (disk select) and **maybe** only the two status registers need to be private for a given disk (?). Check in C65 emulator (easier to modify than MEGA65), if it works by having a disk as drive 0 and having empty drive for drive 1.
2.  Extend the framework to have callbacks for more than one drives, add to the C65 emulator to allow a disk there with the desired `-9` option.
3. Check things in MEGA65 emulation, how we can mount without Hyppo having auto-mounted drive/disk 1 ... Or other trick, maybe the "first hypervisor exit" trigger.

**Comment by lgblgblgb** [comment]
Phase-1 is targeted. Checking if it still works (at least compiles).

**Comment by lgblgblgb** [comment]
**important** now we have doubts (Discord chats) that even C65 ROM is mature enough to be able to use multiple drives, so it can be also the case that it's not an emulation problem with these experimental tries I do here, but the ROM itself is not so much ready to really use more than one drive in a working way :(

**Comment by lgblgblgb** [comment]
STALLING, since it's unclear if it works with the C65 ROM, so is there any need to continue this, at this stage? :-O Also, not sure if MEGA65 can support this, though in theory it has two D81 image mounting possibilities IIRC.

**Comment by lgblgblgb** [comment]
Note to myself: this must be rethought, as I had a bug in F011 emulation (see #118) which could cause the problems make this project impossible so far!

**Comment by lgblgblgb** [comment]
Also, incorrect block cache behaviour may cause problems at least with MEGA65, see: #251

**Comment by lgblgblgb** [comment]
With newer BS ROM it _seems_ to work on MEGA65. The disk image for the second drive is always external, and must be given with `-9` CLI option or using the UI menu. This is because, to expand hardware level MEGA65 emulation for the second drive at MEGA65 (not only F011) register level, it would require a major rewrite of many components, and maybe even using newer Hyppo which is currently not so much possible.

**Comment by lgblgblgb** [comment]
Note: for proper MEGA65 level support (via "mounting mechanism" etc) would require to change many things, quite out of scope of this issue. So for the first try, let's close it. It must be re-visited later in the form of total rewrite about everything done in `sdcard.c`.

**Comment by lgblgblgb** [comment]
New related issue: #314
