### ISSUE TITLE
UI: complete MacOS GUI with new features which already exists for GTK and Windows versions

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#227]
## The problem

Both of the **Windows and and GTK GUIs were updated** by me (LGB) for some new features. However **I can't modify the MacOS code** as it's black magic for me (ObjectiveC calls from C ... and I don't even know Macs at all ... though I still had some mods here and there in the MacOS GUI since then ehmmm, but that's not enough). These features are:

1. implementation of the **save dialog functionality** like the open dialog one (_I can't do this_), original issue: #201 
2. implementation of the "**query back**" interface (_I partly tried even in the Mac GUI code!_), original issue #200 
3. implementation of the "**checked" men item** feature (_that's what I can't do ..._), original issue #200 
4. implementation of the **separator** menu element (_I also can't touch_), original issue #200 

Since the original issues were quite divergent for now, and it's about everything randomly, I close those issues, and put here only the MacOS specific missing features. **Please do not use those mentioned ("original") issues as information source too much, they can be outdated for now, with false information!**

### Branch to use

Currently the best way to fork branch `next` and have work on this, probably in a 'feature branch' first.

#### Warning about changes in UI

It's important to mention, that UI code has changed a bit recently. Since I reorganized things (eg, renaming some source files). Also, I did some modifications in the MacOS UI code as well, though nearly not as much as it needs to have all the features we talk about, in this issue ;) So in nutshell, it's important to have a fresh fork/whatever of the current `next` branch, and working on that then!

### Save dialog

Xemu's GUI layer has a file selector which can be used:

    #define XEMUGUI_FSEL_OPEN    1
    #define XEMUGUI_FSEL_SAVE    2

with the low 2 bits masked (& 3) and check for those constants in the parameter of dialog_mode of function _xemugui_file_selector()_. However, till now, only OPEN was used, but **we need SAVE** as well. So the implementation of function _xemugui_file_selector()_ - better say, its implementations - should check that and offer a SAVE dialog instead of OPEN then. In SAVE mode, it would be nice to warn you automatically if file is being overwritten and asking the user. With GTK it can be done with just some default callback + signal.

See _xemu/gui/gui_gtk.c_ for a sample implementation at function _xemugtkgui_file_selector()_ which also uses _xemugtkgui_confirm_overwrite()_ as a simple gtk-fall-back overwrite warning stuff.

### Query-back interface

This is a way in Xemu's GUI API, that an emulator can dynamically change the menu in some way. More notable, to be able to add/remove the "checked" flag, but there can be other uses as well in the future! An emulator can define (see for example file `ui.c` for MEGA65) a menu item which is "query-back" like this:

    { "System console", XEMUGUI_MENUID_CALLABLE | XEMUGUI_MENUFLAG_QUERYBACK, xemugui_cb_sysconsole, NULL }

Only then - if `XEMUGUI_MENUFLAG_QUERYBACK` is there - the menu builder calls the callback during the menu building process, and use the result only after that. It's up to the callback if it changes something or not. Please not, that the mentioned callback is **the very same** which is called when the menu is activated! This is not a problem, since the callback should have looks like this (with the exact prototype as well):

    void xemugui_cb_sysconsole ( const struct menu_st *m, int *query )
    {
        if (query)
            *query |= (sysconsole_is_open ? XEMUGUI_MENUFLAG_CHECKED : XEMUGUI_MENUFLAG_UNCHECKED);
        else
            sysconsole_toggle(-1);
    }

That is, if parameter `query` is not `NULL` then it's a query-back thing. In this case `query` (as a pointer) holds the flags, which can be modified by the callback. Other than that, in query-back mode, the callback should **not do anything other**. If the `query` is `NULL` then it's a normal call, meaning, the menu is activated. In this case, surely, because `query` is NULL, the pointed value cannot be modified, unless you want a segmentation fault, or something, by de-referencing a `NULL` pointer ;)

**IMPORTANT**: I've tried to "hack" this query-back interface into the MacOS part of the UI. However it is not so useful, without rendering that checked menu stuff, what is the primary purpose to have this feature at all, currently :)

### Checked menu item

This is a way that the menu item visually has a check-mark or not. Though in theory, the menu description by the given emulator can directly asks that, realistically you want to set/reset that with the mentioned "query-back" interface. One easy example for Windows GUI how it's implemented in the GUI core:

    if ((type & XEMUGUI_MENUFLAG_CHECKED))
        CheckMenuItem(menu, xemuwinmenu.num_of_items, MF_CHECKED);

One important point! Just browsing the sources, it seems Windows is not so much consistent with the GTK implementation. That is, the callback **must** set either of `XEMUGUI_MENUFLAG_CHECKED` or `XEMUGUI_MENUFLAG_UNCHECKED` on a query-back request, it's maybe not enough in every case to set checked only (and leave that alone for unchecked state). And be careful not to set both, since it's possible just the result is hmmm unknown :) Honestly my GUI layer is not the best. The problem here that on Windows you can mark a menu item checked later. On GTK you need to create as checkable ... Thus if we don't have CHECKED or UNCHECKED the GTK version won't know that it's a checkable item if it's not checked, so no way to check it by the user ... I should create a better abstraction in the future, but I wouldn't rewrite everything in the GUI as well ... :-/ However this whole paragraph is more problem of the actual UI in the emulators (thus, the users of this API, and not the API implementation itself, which provides that).

Thus in nutshell, having either `XEMUGUI_MENUFLAG_CHECKED` or `XEMUGUI_MENUFLAG_UNCHECKED` shows that menu point item is checkable, and having checked or unchecked state. That's a reason why it isn't just a checked flag, and it's not checked otherwise, since actually we don't have two state but **three** that is (the last - being the fourth - is the invalid case!):

* menu point is checkable and checked (flag: `XEMUGUI_MENUFLAG_CHECKED`)
* menu point is checkable and it's unchecked (flag: `XEMUGUI_MENUFLAG_UNCHECKED`)
* menu point is not checkable at all (flag: neither of flags `XEMUGUI_MENUFLAG_UNCHECKED`  nor `XEMUGUI_MENUFLAG_UNCHECKED`)
* _setting both of the bits would cause **serious problems**, do not do that_

By the way, the code for the callback (checks pointer `query`) for a given emulator (not in the GUI implementation code, but in a GUI user, like MEGA65 target's code) can use a helper macro now for the 'checked stuff'. Like this:

    static void ui_cb_show_drive_led ( const struct menu_st *m, int *query )
    {
        XEMUGUI_RETURN_CHECKED_ON_QUERY(query, show_drive_led);
        show_drive_led = !show_drive_led;
    }

That `XEMUGUI_RETURN_CHECKED_ON_QUERY` is a macro, and basically that expands to this:

    static void ui_cb_show_drive_led ( const struct menu_st *m, int *query )
    {
        if (query) {
            *query |= (show_drive_led) ? XEMUGUI_MENUFLAG_CHECKED : XEMUGUI_MENUFLAG_UNCHECKED;
             return;
        }
        show_drive_led = !show_drive_led;
    }

The examples also show well, that checked status corresponds to the actual state before activation of that menu point, since - of course - the query-back happens before the user clicking (activation) of that menu point. This only can be a problem, if the menu is not rebuilt after that and/or no newer query-back has been done ...

In theory, it's possible to set/reset other flags as well, but currently that makes no sense. In the future it can be useful for other things, including active/inactive menu points. Or "radio button list", which currently done in an odd way to use bunch of checked menu items, and only one of those shows "checked". That's not so nice, and it's actually a **TODO** which is again a thing, I cannot do for Mac, but maybe indeed I can for Windows and GTK ;)

### Menu separator

`XEMUGUI_MENUFLAG_SEPARATOR` `or`'ed to the type in the menu definition should cause to have a separator line **after that** menu item.

### Future works

Not yet, these are not used in other GUI implementations either (I just include these that in can be a future development, but not current the scope at all!):

* radio button list kind of menus
* active/inactive menu items
* some specific windows in the future like "About"
* the common Mac user question: **why there is no usual Mac menu bar, only a context menu** and possible solution?
* try to make menu as async on every platforms somehow (maybe via getting custom SDL signals on user selected menu stuff etc)

**Comment by lgblgblgb** [comment]
@hernandp If you can work on this some time, please comment, than I can assign to you, which is not possible without a comment at least from you as a participant in the issue.

**Comment by hernandp** [comment]
I'll take this. It's a long standing issue. Thanks.

**Comment by lgblgblgb** [comment]
> I'll take this. It's a long standing issue. Thanks.

Thank you, it's yours, now it's official :)
