### ISSUE TITLE
MEGA65: M3wP's MOD player displays only garbage

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#230]
M3wP's MOD player displays garbage on startup (MEGA65 software). According to him, he did not do any fancy, so it seems to be an interesting problem. Note, that also @hernandp 's branch seems to have problem with this. [musak.zip](https://github.com/lgblgblgb/xemu/files/5900101/musak.zip) **Note**: at this point it does not matter if it plays the music or not, or anything, just it's strange it displays garbage when according to the author, nothing fancy VIC-IV feature was used ...

**Comment by lgblgblgb** [comment]
Should be re-visited. With `merger` now there is some visible screen content, however no idea if it matches with MEGA65 or not.

**Comment by hernandp** [comment]
Works with `merger`, including sound and display.

**Comment by lgblgblgb** [comment]
The sound worked before too just not the display. Honestly I've not yet tried this on MEGA65 how it "should" look though.

**Comment by lgblgblgb** [comment]
As far as I see the display problem has gone away with the VIC-IV improvements, so I close this now.

@hernandp Surely, as always, you can comment and/or re-open this issue if you don't agree. Thanks.
