### ISSUE TITLE
MEGA65: VIC-IV RRB does not honour Y offset bits when drawing overlay characters

### ISSUE THREAD

**Issue by geehaf** [lgblgblgb/xemu#232]
I have Raster Rewrite Buffer asm code working and able to overlay & smoothly reposition each character's x-position in 256 FCM mode. However when I change bits 5-7 in Screen RAM Byte 1 (this byte is part of the 16 bit word that holds the char's x position for the RRB) to try and alter the y-position (i.e. where VIC IV starts reading the char def bytes from) I cannot get it to respond,i.e. the chars look the same. 

**Used version of the project**
I am using Hernan's branch of the emulator and I have tested on "Zipped 64-bit Windows binaries 20210302012957"

**To Reproduce**
I will code up and attach an example program.

**Expected behavior**

**Screenshots**

**Computer/Device (please complete the following information):**
 - Windows 10 64 bit

**Additional context**

**Comment by lgblgblgb** [comment]
Thanks for the info. Fairly expectable, MEGA65 changed a LOT since the VIC-IV emulation was written, I guess you can find tons issues like this more :) Though I would pass this to Hernan to have a look (currently he is more in VIC-IV emulation topics), however please note, that this can take a while, to catch MEGA65's current state (and when we are there, MEGA65 will be away then again, I guess, hehe) :-)

**Comment by geehaf** [comment]
Thanks LGB. If I can help in ANY way let me know. I have programming
skills including C & 6502 and very happy to perform testing.

Regards,

George

**Comment by hernandp** [comment]
@geehaf  do you have a little code piece to test?

**Comment by geehaf** [comment]
Hi - I've added a 'testrrb.prg' test file contained in the zip archive. When you run this you will see a column of 8x8 256 colour chars swinging right->left. I think you should see movement in the y direction of column's graphic data when the fix is in place as bits 5-7 of Screen Ram Byte 1 (same word as the GOTO X bit being set) is being cycled through values 0 -7 continuously.

I hope this helps.
P.S. the test file is large as I re-purposed my recent m65 demo thus has a large amount of graphic tile data - Sorry. :)

[rrbtest.zip](https://github.com/lgblgblgb/xemu/files/6096555/rrbtest.zip)

**Comment by geehaf** [comment]
HI Hernan - I've added a comment and attached what I hope is a test .prg
file.

**Comment by hernandp** [comment]
Hi @geehaf  did you test your rrbtest in MEGA65 hw?  I could not make it to work.

**Comment by geehaf** [comment]
Hi Hernan

Thanks for your note.

I don't have mega65 HW so unfortunately I could not test. I was working
"blind' when I pulled together the code. Perhaps there is some test code
for RRB that Paul has?

Let me send you details on what my code was doing and see if that ties back
to your changes.

Regards

George

**Comment by geehaf** [comment]
[GK RRW code info.pdf](https://github.com/lgblgblgb/xemu/files/6251505/GK.RRW.code.info.pdf)

I can provide more details if needed.
Cheers, George

**Comment by lgblgblgb** [comment]
Is this the same issue as #255 about the "Y positioning"?

**Comment by lgblgblgb** [comment]
@geehaf Please see #255 and if it fixes the problem. Since it's about the same issue, I close this now. In case of problem still, please comment issue #255 instead. Thanks!
