### ISSUE TITLE
MEGA65: VIC Y-scroll register causes chars to be drawn incorrectly when using values 0 - 6

### ISSUE THREAD

**Issue by geehaf** [lgblgblgb/xemu#233]
**Describe the bug**
VIC Y Scroll causes screen chars to be drawn incorrectly when using values 0 - 6

**Used version of the project**
I am using Hernan's branch of the emulator and I have tested on "Zipped 64-bit Windows binaries 20210302012957"

**To Reproduce**
Enter this basic poke when in C64 mode:

poke 53265,peek(53265)and248or2

Same behaviour is exhibited when using the VIC IV $d04e and $d04f registers

**Expected behaviour**
Screen should scroll in y direction by a pixel without char corruption.

**Screenshots**
![image](https://user-images.githubusercontent.com/79896622/110204362-b2018300-7ec6-11eb-96f2-d4bcc0f8f25f.png)

**Computer/Device (please complete the following information):**
Windows 10 64 bit

**Additional context**

**Comment by hernandp** [comment]
This is already fixed my friends.

**Comment by geehaf** [comment]
Great work and great news. Looking forward to the next release on the xemu
page (https://github.lgb.hu/xemu/).

**Comment by lgblgblgb** [comment]
I close this, because of being resolved by @hernandp

**Comment by geehaf** [comment]
Thanks!
