### ISSUE TITLE
MEGA65: Fix VIC-IV SPRPTR16 register to proper behavior

### ISSUE THREAD

**Issue by hernandp** [lgblgblgb/xemu#245]
In issue https://github.com/MEGA65/mega65-core/issues/339  there is a description of the proper way MEGA65 uses 16-bit sprite pointer table.  In Xemu we implemented the "official book documentation" way but it is not correct.

**Comment by lgblgblgb** [comment]
I close this, as I suppose, the fix from Hernan is the solution here.
