### ISSUE TITLE
MEGA65+C65: Reading outputs bits from $DD00 doesn't work, leading to changes to VIC-II (and VIC-III 32K) bank

### ISSUE THREAD

**Issue by smf-** [lgblgblgb/xemu#250]
Output bits in $dd00 cannot be read back in either xc65 or xmega65 & instead $ff is always returned, but software including the kernal expects to be able to read output bits so that it can modify other output bits and write the value back.

For example when this code executes

CPU: at $EE8E opcode = $AD LDA $nnnn A=0D X=03 Y=00 Z=00 SP=EC^M
CPU: at $EE91 opcode = $09 ORA #$nn A=FF X=03 Y=00 Z=00 SP=EC^M
CPU: at $EE93 opcode = $8D STA $nnnn A=FF X=03 Y=00 Z=00 SP=EC^M

it will replace the vic2 bank bits with 11, which may have gone unnoticed as it's the default. However if the bank is >$4000 then it will be reset to $0000 and the display will be incorrect.

I've downloaded the latest binaries and the latest master source, I've visually examined the other forks to see if it has been fixed and I can't see anything that I think would fix it.

To reproduce:

GO64
10 POKE56576,0
20 OPEN15,8,15,"I"
30 OPEN2,8,2,"#"
40 OPEN8,8,15,"I"
50 CLOSE8
60 PRINT#15,"U1: 2 0 1 0"
70 GET#2,A$
80 INPUT#15,A,A$,B,C:PRINT A,A$,B,C
90 CLOSE15
100 CLOSE2
110 FOR I=0TO2000:NEXT
120 POKE56576,255

The display should change (usually displaying a blank screen on xc65 and xmega65 or displaying lines in vice x64sc) as it moves vic2 to $c000 & the error 70    NO CHANNEL    0     0 will be output, however it should not appear until the loop finishes and the final POKE to move vic2 back to $0000, but due to $dd00 reads not working it will change the bank back almost immediately.

In my original use case the screen turns to garbage as there is no valid data for vic at $0000 to $3fff and it's not possible to reliably work round the issue.

I tested this on windows, but I would expect this to happen on all operating systems due to the cia_port_in_dummy() method always returning 0xff.

**Comment by lgblgblgb** [comment]
Thanks, nice analysis and report. Yes, that was kind of "debug stuff" remained that way and never corrected. I guess there can be tons of things like this only showing up as bug later, when somebody notices it, since the project recently (on the MEGA65 emulation, and C65 emulation is mostly forgotten/not used by too much people anyway) is more about new MEGA65 features (and programs using mostly MEGA65 features, where there is free placement of various VIC related things, eg no need for VIC banks at all) and not so much legacy ones. Still for sure, that's a bug.  I'll handle it as soon as I get there.

**Comment by lgblgblgb** [comment]
In `next`.

**Comment by smf-** [comment]
> In `next`.

I just built 'next' and it seems to have fixed the issue, however it is unusable. The window title is "Xemu [7% 1409%] running 40.50mhz" and switching away and back gives a "not responding" message.

Is this expected? Is there anything I can do to get back to 100% speed, that I get with master?

**Comment by lgblgblgb** [comment]
No idea, shouldn't be any connection, just that CIA little modification. Probably you enabled heavy debugging, like CPU debugging? That creates lots of I/O for sure and cannot be done in real-time of course. Also comparing to the master, I cannot tell anything about that, master is so old, that I even can't remember now for the differences. I abandoned master mostly, there will be no any change in that, in fact, as name suggests `next` is meant to be the "next master".
