### ISSUE TITLE
MEGA65: Issues with current raster rewrite buffer

### ISSUE THREAD

**Issue by deftmega** [lgblgblgb/xemu#253]
Issues with current RRB, please see demo code:

https://github.com/smnjameson/M65_Examples/tree/main/1-RasterRewriteBufffer

- behaves differently to HW, seems to crop lines at 20 chars

It is expected to look like this:
![expected](https://user-images.githubusercontent.com/3924427/118886913-df70a100-b8f9-11eb-87c0-ea191fb4c5b4.png)

but instead looks like this:
![actual](https://user-images.githubusercontent.com/3924427/118886936-ea2b3600-b8f9-11eb-9893-711477f7efaf.png)

**Comment by hernandp** [comment]
Analyzing this.  Please assign issue to me @lgblgblgb , thanks!

**Comment by lgblgblgb** [comment]
@hernandp Yours :) And thanks. And btw, please do not forget to always check the `merger` tree for updates first, since I have the habit to do "random" changes ;)

**Comment by lgblgblgb** [comment]
Oh btw, it seems (just realized ...) that it's the same issue as #265 was just posted. So the fix there seems to fix this one too. I close this now, being a duplicate (it seems).
