### ISSUE TITLE
MEGA65: "Use Palette ROM" $D030 bit 2 - inverted behaviour

### ISSUE THREAD

**Issue by smnjameson** [lgblgblgb/xemu#258]
When bit 2 (value 4) is set of $d030 the VIC should use RAM palette entries as per hardware, on Xemu behavior is inverted setting bit 2 causes the ROM palette to be used for 0-15

MERGER branch

![image](https://user-images.githubusercontent.com/4640763/119251325-f46d5e80-bb9d-11eb-8c8c-cbee1adcf7df.png)
See testing vs hardware

I was able to get palette to display correctly by inverting the bit in $d030 as described

**Comment by lgblgblgb** [comment]
Honestly, I'm lost, what value 1 means, using nor not using ROM ;) But AFAIK you're right and should be inverted. Note, that it's "bit 2" (just value 4 for that bit position), hopefully you don't mind that I edited the issue not to cause confusion later. Hopefully the commit above fixes the issue. The situation now with that:

![x](https://user-images.githubusercontent.com/884916/119254973-7a4ad300-bbb9-11eb-8c2f-6830f42f52d4.png)

**Comment by lgblgblgb** [comment]
Committed, builds for `merger` are available at the usual place. I close this now, if it's still not OK, you can re-open it for sure, if it's really this single issue with rom/ram palette selection, still. Thanks for the report!!

**Comment by smnjameson** [comment]
Note to self: Sleep before submitting bugs. Thanks for the quick fix !
