### ISSUE TITLE
MEGA65: VIC-IV 16 Color mode char errors

### ISSUE THREAD

**Issue by smnjameson** [lgblgblgb/xemu#264]
The following behaviour is observed when comparing the output of the included 16 color mode char tests between hardware (R3 devkit) and the latest Xemu merger branch:

**Hardware**
![image](https://user-images.githubusercontent.com/4640763/120342961-3316bd80-c2f0-11eb-8bdc-4b480c36e564.png)

**Xemu**
![image](https://user-images.githubusercontent.com/4640763/120343077-4e81c880-c2f0-11eb-85b9-14def6809851.png)

1.  Color index 0 should be transparent but is not.
2.  Horizontal flipping does not appear to work (2nd and 4th character are not flipped correctly)
3.  Palette changes have no effect (this should be achieved by setting bits 4-7 of byte 1 of Color ram to choose a 16 byte offset into the palette)

I would deem these three issues to be pretty urgent as they will hamper the Millfork challenge starting later this week. Without them I will have to rework the challenge to another date.

[vic4tests.zip](https://github.com/lgblgblgb/xemu/files/6580061/vic4tests.zip)

**Comment by smnjameson** [comment]
Excuse the awful code advice, i don't really do much C but...

all in 
https://github.com/lgblgblgb/xemu/blob/merger/targets/mega65/vic4.c


Issue 1
line 1023 to:
`*(current_pixel++) = char_data ? palette[char_data] :  palette[bg_color];`


Issue 3 would require passing in bits 4-7 of color ram byte 1 to this same method and adjusting line 1023 again to:
`*(current_pixel++) = char_data ? palette[ colorByte1Bit4to7 | char_data ] :  palette[bg_color];`

**Comment by lgblgblgb** [comment]
Issue #254 seems to be a duplication now for this issue which has in-depth look and examples (thanks to Shallan). Let's keep this one, instead of that, then.

**Comment by lgblgblgb** [comment]
@smnjameson You're probably right, at least line 1023 currently indeed does not deal with transparency at the current form at all. Well, knowing C is not so much important always, if the logic can be seen in the code to at least some degree ;) I haven't checked anything yet more (or @hernandp , I guess) but that line 1023 is very suspect even if just I have a look on it, indeed.

**Comment by lgblgblgb** [comment]
Oh, btw, that issue 3 is new to me, I haven't even known there is a feature like this for now in mega65-core :-O Which does not mean it's a very new feature, just it's new for me, that's all ;)

**Comment by lgblgblgb** [comment]
Issue 2 is a problematic one, since 16 colour char mode rendering is very much separated from the other char mode handling/emulation and does not to ANYTHING about attributes like flip etc. Now it's a very interesting topic, that the 16 col text mode renderer should be make "smarter" but effectively duplicate much of the code of the "other char renderer", or fuse them together not to have a different code path (but it slows down any of the cases ...). Should be discussed with @hernandp as most of the newer VIC-IV emulation code was his work recently.

**Comment by hernandp** [comment]
Hi guys. Yes, this is probably due to handling the 16-Nybl mode with *bare bones* features.   Needs more work for sure.   I will review the transparency issue first.

**Comment by lgblgblgb** [comment]
Though I may be confused with the code layout, at the second glance I am not sure only the char row rendering is different and the attribute (like flip etc) is common. My bad.

**Comment by smnjameson** [comment]
Vertical flip works fine just not horizontal flip. Though this of course would require some nybble flipping due to the nature of the data, probably fastest through a look up table

**Comment by hernandp** [comment]
I'm in the middle of moving to a new house -you know what kind of mess this is-  but I will try to do a fast patch for this problem. And thanks for the victests file :)

**Comment by lgblgblgb** [comment]
> I'm in the middle of moving to a new house -you know what kind of mess this is- but I will try to do a fast patch for this problem. And thanks for the victests file :)

Off-topic ;) Have a good move then. And do not forget the sources to be moved as well ;)

**Comment by lgblgblgb** [comment]
I think, line 1023 has to be modified as (not as easy as looks like first glance):

               if (XEMU_LIKELY(enable_bg_paint))
                       *current_pixel = palette[char_data ? char_data : bg_color];
               else if (char_data)
                       *current_pixel = palette[char_data];
               current_pixel++;

And surely bg color should be passed to the function, the caller most provide it, etc etc, as well.

**Comment by lgblgblgb** [comment]
Well, with the latest commit, transparency at last **seems** to be ok with that test. But as far as I can see, this is very much a problem in other modes as well, the commit above targets 16 colour mode now ...

**Comment by lgblgblgb** [comment]
The result so far (hflip is still missing):

![xemu](https://user-images.githubusercontent.com/884916/120384286-404e9f00-c326-11eb-8a5f-38e9b98f59e1.png)

**Comment by lgblgblgb** [comment]
Note, that the actual solution is more simple now with my latest commit what I supposed initially (and hopefully it's RRB compliant as well, ie bg_paing disabled proof):

                if (char_data)
                        *current_pixel = palette16[char_data];
                else if (enable_bg_paint)
                        *current_pixel = bg_sdl_color;
                current_pixel++;

Also, palette16 now is a pointer passed to the (inlined ...) function taking account the palette offset, so no need to do extra pointer arithmetic inside the char row rendering loop.

**Comment by lgblgblgb** [comment]
hflip **seems** to work now as well. So all the three issues seems to be addressed in this ticket, hopefully well enough ...

**Comment by lgblgblgb** [comment]
Please give a feedback if this issue can be closed ... As it's only tested with "vic4tests", maybe it cannot be called as throughout testing method from me and issues can be found still. Thanks.

**Comment by lgblgblgb** [comment]
I consider this being done, since no more complains since a while :)
