### ISSUE TITLE
MEGA65: RRB GOTOX positions incorrect in 40 column mode:

### ISSUE THREAD

**Issue by smnjameson** [lgblgblgb/xemu#265]
[vic4tests.zip](https://github.com/lgblgblgb/xemu/files/6585555/vic4tests.zip)
 
The 16 Color 40 column RRB test above should show two green dots moving the full width of the screen. These green dots are using the RRB to draw, as such there is a third GOTOX to terminate the line on the far right of the screen (x=320). Note on XEMU this third dot is visible halfway across the screen and the two moving dots only move half the width also.

XEMU:
![image](https://user-images.githubusercontent.com/4640763/120506194-99b5dd00-c3bd-11eb-87c0-09d1250117f4.png)

HARDWARE:
![image](https://user-images.githubusercontent.com/4640763/120506255-a9cdbc80-c3bd-11eb-9b25-71b91bceaef4.png)

Note changing the line 1147 in https://github.com/lgblgblgb/xemu/blob/merger/targets/mega65/vic4.c

`current_pixel = pixel_raster_start + xcounter_start + (char_value & 0x3FF) * (REG_H640 ? 1 : 2);`

Partially fixes the GOTOX in 40 column mode but does still draw the terminating RRB layer on top of the border:

![image](https://user-images.githubusercontent.com/4640763/120506931-485a1d80-c3be-11eb-8c2a-1ccb8544f5ae.png)

As such I have not created a pull request, as I'm not sure where to stop this happening.

**Comment by lgblgblgb** [comment]
I think, you forgot about xcounter to adjust as well. See the commit above (however honestly it's a mess since now it's combined with some other changes. Please note that this branch will not be merged ever, but manually, so many insane commits we don't want to keep in the commit log of the stable release).

**Comment by lgblgblgb** [comment]
#253 seems to be the very same issue, as it turned out. I close that. If we can still have problem covers this or that bug, we should focus on this newer one.
