### ISSUE TITLE
D81ACCESS: virtual D81 from PRG file feature is limited in max PRG file size which does not make sense (38000 bytes)

### ISSUE THREAD

**Issue by deftmega** [lgblgblgb/xemu#271]
Only some .PRG files get detected when using drag'n drop into the XEMU window (C65/MEGA65 mode executables).

Please find attached one working (kalle65.prg) and one not working (megadots.prg).

[Desktop.zip](https://github.com/lgblgblgb/xemu/files/6604782/Desktop.zip)

**Comment by lgblgblgb** [comment]
Drag'n'Drop feature is designed for D81 images. The logic, that if the size is exactly D81 default size, it is mounted as disk image. If not, but "small enough" it's treated as PRG file and "virtually" converted to D81 image and presented that way. However, the size was limited to 38000 bytes for whatever reasons I can't even remember right now ;) Note, that I can raise that limit, however it won't be a true solution still but surely at least kind of cure the typical situation like this.

**Comment by lgblgblgb** [comment]
According to Bit Shifter, $D700 is the max PRG size which can be safely LOADed with his closed-rom flavours. So I'm about raising the limit to that size (even that, if loaded in C64 mode, it can be - ? - already a problem, but that's other question).

**Comment by lgblgblgb** [comment]
Also, about adding a popup window disappear on dropping file. So you can mount the dropped file as D81 (being a real D81, or converted a file to be on a D81 so can be loaded then) _or_ using PRG run, which is a more faster and direct approach but bypasses the normal LOAD mechanism.

**Comment by lgblgblgb** [comment]
Just to have some love for the C65 emulator, the drag&drop question thingy should be ported there as well ;)
