### ISSUE TITLE
C65/Mega65: problems with newer ROMs?

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#28]
I'm unsure on this one. But it seems any ROM for C65 newer than the currently used, and old one (910111) have serve issues. You cannot even enter a BASIC line, getting `?PROGRAM MANGLED` error message. `DIR` works, but `LOAD` (usually) gives `?SCREEN NOT OPEN ERROR`. Trying to `LIST` a BASIC program results in memory garbage printed on the screen without end. Interestingly, if you could load something (sometimes work) then you **can** enter BASIC lines without the `?PROGRAM MANGLED` error, and even `LIST` works. For me it seems, these ROMs are totally unusable, and should be avoided.

**HOWEVER**: there is the high possibility, it's only a bug in my emulator! So, firstly it should be decided which is the case ... And if it's an Xemu bug, it must be fixed, of course.

**Comment by lgblgblgb** [comment]
It **seems** this is the case with the FPGA board as well, with newer ROMs, so maybe it's not the emulator, but really the newer ROMs are this buggy!

**Comment by SvOlli** [comment]
This is no bug, but a feature. The later ROMs assume that a 65-DMAGIC chip is in the board. This error occurs when a 51-DMAGIC is used with a later ROM. (Found this one in some printed 1997 C65 German usergroup document.)

Best way to understand the change in the DMAgic change might be to disassemble the 910626 ROM (which is stated to be the last with 51-DMAGIC support) and 910828 (first for 65-DMAGIC) and compare how these two access the DMAgic.

**Comment by lgblgblgb** [comment]
Aha, thanks for your comment. I also had two conclusions: either the ROM was so experimental that it didn't worked to well, or some compatibility problem between the ROM and the hardware what I emulate, ie the newer ROMs expects something different. But honestly, I didn't know that it's exactly the DMA thinggy, so again, thanks. Now I am not sure, but as far as I remember, later revisions of DMAgic uses longer DMA list 'entries' (maybe just one byte or so), though I don't remember about the exact details. Maybe I try to emulate both (with possibility to select DMA revision to emulate) but first, I should know more about the extra things dropped in later, during the C65 development at the DMAgic line (even the current emulation I just guess the MIX command, the minterms etc ... maybe it does not work that way, though I don't think those are used by the base ROM anyway).

**Comment by SvOlli** [comment]
Maybe the easiest way to understand die differences would be to add "DMAgic logger" to the emu.
Just writing out the address of the "DMAgic script" and dumping the head of that one, like 4 lines of 12 bytes each. Documentation is no use in this case: the one embedded in the document as 2.7 is just a rough overview and the addendum is just for one configuration. My guess is, that it's for the first one, because that's the one that's working in the FPGA and your emu. So for the newer one we might be forced to rev'eng it some way or another. Sniffing the data fed by the newer ROMs might work...
