### ISSUE TITLE
MEGA65: VIC-IV bitplane mode emulation has some problem in branch merger in V400

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#280]
Though branch `merger` is very much superior compared to previous VIC-IV emulation terms, there is still some odd thing happening in bitplane mode. It seems the problem is there, if V400 mode is tried to be used, ie 320x400 or 640x200. 320x200 and 640x200 seems to be fine. It's hard to compare with `next` as it does not support V400 at all. The odd thing (no idea if it's Xemu related): tests with V400 seems to hang BASIC as well, ie you can't exit by pressing a key. Though I have no idea why can be the case, as it's nothing to do with display ...

Test programs (BASIC 65 programs, written by BitShifter): [tests.zip](https://github.com/lgblgblgb/xemu/files/6722311/tests.zip)

Faulty result (in this case `640x400.prg`):

![screenshot-20210627-231336](https://user-images.githubusercontent.com/884916/123559608-5b81c280-d79d-11eb-95e0-d66b302acfbc.png)

**Comment by lgblgblgb** [comment]
Also needs to be checked that no problem with other modes (not bitplane!) with V400, maybe this is a common problem, not restricted to bitplane mode only?

**Comment by lgblgblgb** [comment]
**NOTE** it seems the problem is bitplane specific only (at least this kind of problem) and was an error not even handling the odd/even scanline selected bitplane register low/high nybble :-O

**Comment by lgblgblgb** [comment]
**NOTE2**: maybe DAT implementation also need to be adjusted when V400 is used!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Edilbert** [comment]
The BASIC 65 garphics do NOT use DAT

**Comment by lgblgblgb** [comment]
> The BASIC 65 graphics do NOT use DAT

I know (we have discussed before) that BASIC do not use DAT, but anyway, from the point of hardware emulation, DAT should be fixed too, what I meant.

**Comment by lgblgblgb** [comment]
Also, from hardware emulation perspective, Xemu does not emulate the attribute mode for bitplanes .... Maybe not even MEGA65 does this though hmmm :)
