### ISSUE TITLE
MEGA65: Incorrect VIC-II bitmap fetch address

### ISSUE THREAD

**Issue by hernandp** [lgblgblgb/xemu#284]
**Describe the bug**
During character fetch, either in bitmap or text mode, the VICII bitmap address is set to CHARSET addr.  This fails when e.g CHARSET is set to 14336 (with bits $D018 1-3 to 1110) since the only considered bit is 3 for bitmap. 
So the effective VIC2 bitmap address should equal to MEGA65 24-bit Charset address with masked bits 0-12.  This will keep bitmap (13) and DD00 bank (14-15) plus the upper MEGA65 additional bits. 

The following program can be used for testing:

![image](https://user-images.githubusercontent.com/4740613/126518464-7f06fd11-24a3-4b74-bd3b-65039f59c456.png)

Correct output is (both in HW/xemu):
![image](https://user-images.githubusercontent.com/4740613/126518524-0950c42f-3fee-4e8f-b831-cd662fbf9072.png)

Incorrect output (fetch is displaced from 14336 instead of 8192):
![image](https://user-images.githubusercontent.com/4740613/126518712-41c0d1cc-e2e4-4d5d-8209-43551df4c6b8.png)

Use BASICRAS.D81 provided for additional test.
[BASICRAS.zip](https://github.com/lgblgblgb/xemu/files/6857059/BASICRAS.zip)

**Comment by lgblgblgb** [comment]
Thanks! Merged to `merger` sounds funny ;) Btw I've edited your text above, since the hashmark number syntax creates references to other issues ... Unfortunately even after edit now it seems references remains at the target issues. Anyway, it won't kill me, just odd, that once it's done github does not provide any way to remove.

**Comment by hernandp** [comment]
> Thanks! Merged to `merger` sounds funny ;) Btw I've edited your text above, since the hashmark number syntax creates references to other issues ... Unfortunately even after edit now it seems references remains at the target issues. Anyway, it won't kill me, just odd, that once it's done github does not provide any way to remove.

You re welcome.  Yeah that automatic referencing is useful but sometimes a bit odd ;)

**Comment by lgblgblgb** [comment]
Is there anything left here or can I close this issue?

**Comment by hernandp** [comment]
@lgblgblgb  It is done.  Close this ;)
