### ISSUE TITLE
MEGA65: MAPL and MAPH values in uart monitor reported incorrectly

### ISSUE THREAD

**Issue by gurcei** [lgblgblgb/xemu#286]
**Describe the bug**
Recently, I was debugging an openrom matter via xemu, and the uart-monitor reported the following values:
```
PC   A  X  Y  Z  B  SP   MAPL MAPH LAST-OP     P  P-FLAGS   RGP uS IO
5991 00 F7 08 1E 00 01F6 0200 4000 A5       22 00 --E---Z-
```
* MAPL = 0200
* MAPH = 4000

The values didn't see quite right to me, so I compared it against what my devkit reported:
```
PC   A  X  Y  Z  B  SP   MAPH MAPL LAST-OP In     P  P-FLAGS   RGP uS IO ws h RECA8LHC
5670 00 FF 0A 00 00 01F6 0000 4200 2068FA  00     23 ..E...ZC ...P 3C -  00 - .....lhc
```
* MAPH = 0000
* MAPL = 4200

Some differences are:
* xemu's uart monitor reports MAPL first, then MAPH, it should be the other way around
* The upper nibble values are the wrong way around (MAPL's upper-nibble of '4' has gone into xemu's MAPH upper nibble, and similarly for MAPH's upper-nibble)

I don't mind fixing this (inside "mega65.c" - m65mon_show_regs()), but if you want to beat me to it, no problem.

**Used version of the project**
I was on the merger branch

**Expected behavior**
Match devkit results

**Comment by lgblgblgb** [comment]
Thanks for reporting. According to my faint memories, you've already mentioned this once in the past, just somehow I forgot, thanks  to write an issue on it. I'll have a look on it.

**Comment by gurcei** [comment]
Just to help with the recall of the history of it, previously in xemu, the MAPL and MAPH were missing the upper nibble entirely (and just reporting '0' for that nibble).

I had added support for that upper nibble in my work on that uart-monitor branch (which I think got merged back to 'merger' branch?).

So yeah, looking back, seems like I applied the wrong upper nibble to the wrong MAPL/MAPH, perhaps due to me not noticing they were inverted compared to the devkit's ordering of them

**Comment by gurcei** [comment]
I've added a commit on a branch I've parked myself on to resolve this. The 'r' command now outputted the correct format that matches the devkit:
```
PC   A  X  Y  Z  B  SP   MAPH MAPL LAST-OP     P  P-FLAGS   RGP uS IO
FA6A 00 00 08 00 00 01F5 0000 4200 A9       22 00 --E---Z-
```
Wasn't sure of your preference on which branch you wanted this fix. If you like, you're welcome to cherry-pick the commit to whichever branch is suitable.

**Comment by lgblgblgb** [comment]
Hi! Thanks a lot, the relative silence from my side is because of the holiday season, I'm away usually at the weekends but working a lot during workdays, and now two weeks "real" holiday staying at a hotel then at my parents, etc, during the next two weeks with my family. So I'm not sure when I have opportunity to do MEGA65 works other than just quick chats on discord and such. We'll see :)

**Comment by gurcei** [comment]
No probs man, no pressing urgency for this, I've got the fix for my present needs, and it can make its way into other branches whenever convenient. So enjoy your well-deserved holiday! :-)

**Comment by lgblgblgb** [comment]
**Please comment/append at https://github.com/lgblgblgb/xemu/discussions/335**

**Comment by lgblgblgb** [comment]
Closing now in favour or https://github.com/lgblgblgb/xemu/discussions/335
