### ISSUE TITLE
MEGA65: Legacy bitmap modes always assumed at 320-pixel width

### ISSUE THREAD

**Issue by hernandp** [lgblgblgb/xemu#287]
In our current code, bitmap modes are always assumed to be 320 pixel wide, even when it is possible to switch to VIC-II legacy BMM and play with the MEGA65 VIC-IV registers to get a 360 pixel display (45*25).

I have the test program ready and I'm working on a fix, so I can take this. Thanks.

**Comment by lgblgblgb** [comment]
Thanks for the PR! I certainly will have a closer look hopefully still today. Btw, without even have too much chance to check it out right now (work time), doesn't it break other things, like linestep/display correctness in other modes than the title mentioned "legacy bitmap modes"?

**Comment by hernandp** [comment]
I can run more examples, but I think the hardcoded 320 width was only used in legacy modes , both hires and multicolor (check both branches).  The VIC-IV "native" modes already considered the LINESTEP register.

**Comment by lgblgblgb** [comment]
Ah. OK thanks for the info. I was not sure if that information was taken account by native modes, or some changes there, or not, but as I mentioned I had no time _yet_ to really see your changes in context too much, "surely" I have time to write messages here and there all the time though even during work time, that'[s my bad habit ;)

**Comment by lgblgblgb** [comment]
Has been merged, looks fine for me. Closing the issue now. Thanks again.
