### ISSUE TITLE
MEGA65: AnotherWorld port (preview) for MEGA65 has a display issue

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#304]
The great AnotherWorld port to MEGA65 has a very interesting display issue: at the right side of the screen a fixed part of rectangular area is flickering. Very strange, indeed, as it's always a fixed and well bounded, and relative small area of the screen where there is problem.

So far, I know, that AnotherWorld uses two screens (ie, different video memory addresses), rapidly changing between them. The flickering is caused because only one screen has this problem, the other is not. I have no idea though why, and why only a part of the screen still! Probably it has something to do with character attributes being different between the two screens, and Xemu does not do the very same what MEGA65 do, thus effecting the result.

## An old issue

In issue #289 there was a more serious problem with running AnotherWorld on Xemu, that has been resolved, but this more minor (but still very annoying) bug remained. There are other partial information fragments which may can help here as well. Or not ;)

**Comment by hernandp** [comment]
Tested with current Xemu `next`, still happens.

**Comment by lgblgblgb** [comment]
New information from Majikeyric: he has concluded that the problem only appears when glyphs are from the memory area which would be the "C65 colour RAM", ie the 2K area at `$1F800`. Having a second look, it seems my original thoughts here failed badly. Ie, my plan was to update both of "real fast RAM" and the "colour RAM" when writing that memory area, so they are in sync, but the in VIC-IV emulation some don't need to check special cases all the time. However looking at the source, as far as I can see now (and remember my code ...) it's not the case! So probably this is the only problem which secretly could effect many other things as well.

Big thanks to **Majikeyric** for his notification about the possible root cause here.

My plan: I will check if it's really the problem. If it is, I make a fix, also closing this issue, and opening a new one, since then this problem is a wider problem than only AnotherWorld, and it's just a fortunate that no other developer has faced it yet. Also a TODO for me: check is `configure` problem is related (ie, Xemu cannot run configure since a while for unknown reason, and since it's in the colour RAM by default on power-up, it's very much a suspect now in my eye).

**Comment by hernandp** [comment]
Nice finding!
Maybe we can craft some  quick  test program?

**Comment by lgblgblgb** [comment]
Closing this issue and moving to #361 as it's a more generic issue than only being AnotherWorld-specific.

**Comment by lgblgblgb** [comment]
> Nice finding! Maybe we can craft some quick test program? 

Oh, just noticed your message here, after closing the issue. In short, well, I am not planned to do a test for this, since it's kind of straight-forward to do, _after_ I realized what is the nature of problem, I would assume it's a VIC-IV emulation bug (what else can be? hehe ....), surely it's hard to imagine a memory management/decoding issue, since those would "surly effect almost anything so the machine wouldn't even 'boot'". Well we see, assuming things are not the best approach always ...

**Comment by lgblgblgb** [comment]
Though it seemed to be a VIC-IV emulation issue, it was **not** but a memory addressing issue! For more, see: #361

**Comment by hernandp** [comment]
Good catch @lgblgblgb!
