### ISSUE TITLE
MEGA65: problem with multiple emulated FDC drives when copying files/blocks between them

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#314]
Multiple drive support has been already implemented #219. It works quite well, some can `DIR` either of the drives, `LOAD` files, and so on. However it seems, rapid change of active drive can trigger a problem. This is demonstrated best, with try to use `COPY` command to copy files, or even `BACKUP` which just copies a disk to another one, at block level.

Xemu currently keep a private copy of status A and B registers for each drives. Maybe that's the problem, and it shouldn't be done this way.

This problem may affect C65 as well, since F011 emulation core is shared between C65 and MEGA65 emulators. But hard to tell, as the C65 emulator can run only the original C65 ROMs which are so much unfinished and buggy that hard to distinguish between emulation problems and ROM bugs. Current problem with MEGA65 is with the closed-ROMs project, which is a greatly enhanced, bug fixed, etc version, but it does not run on C65 any more.

Also there can be problems with other registers / state info not to made shared, which should be. Investigating now with checking all registers about possible problematic scenarios because of the private/shared state of given info/registers.

**UPDATE**: in #315 some exactly related details has been reported by @jimnicholls , I've also written above.

**Comment by lgblgblgb** [comment]
Marking this issue "WIP" so others can see, I'm working on it already, which I forgot to do :(

**Comment by lgblgblgb** [comment]
A bit delay in the process ...  As mentioned in #315 things like that (with other issues as well), thought, that the problem is with Xemu, and probably the FDC emulation's fault, let it be head info is not private to drive, or other registers. However now it seems, that it can be a ROM bug. Which can lead, that `COPY` command from some unknown reason in the ROM ends up trying to use the IEC bus, even if it's nothing to do with the IEC. On the real hardware, it's usually not a problem as it won't work this way too much. But on Xemu, since Xemu does not emulate the IEC bus, not so much any pull-up resister config etc either with the CIA ports, the ROM stuck at the incidentally  used IEC code.

I must wait for the ROM fix, to really judge on this not to spend my time to fix something which is not the issue.

**Comment by SydneyUni-Jim** [comment]
Putting this here before it leaks out of my grey matter. Specifically with the `COPY` bug, the ROM tried to [request the fast serial protocol](https://www.c64-wiki.com/wiki/Fast_serial_bus_protocol#How_the_controller_requests_the_fast_protocol). It hung because CIA 1's shift register full/empty flag ($DC0D bit 3) never becomes set.

**Comment by lgblgblgb** [comment]
> Putting this here before it leaks out of my grey matter. Specifically with the `COPY` bug, the ROM tried to [request the fast serial protocol](https://www.c64-wiki.com/wiki/Fast_serial_bus_protocol#How_the_controller_requests_the_fast_protocol). It hung because CIA 1's shift register full/empty flag ($DC0D bit 3) never becomes set.

Thanks for the clarification. Do you have any idea if it's fixed (or will be fixed) in some "official" ROM version?

**Comment by lgblgblgb** [comment]
I am not sure if it's still an issue. I'm closing this now. If there is anything new info/bug/etc still in this topic, please comment.

The fast serial IEC protocol try by the ROM has a workaround now since commit 33d70ae691377782ff8b7995baeb0c63899bcc38
