### ISSUE TITLE
Bugs of missing closing files

### ISSUE THREAD

**Issue by ryancaicse** [lgblgblgb/xemu#318]
**Describe the bug**
`fclose(fp); ` should be put in `fail:`?

https://github.com/lgblgblgb/xemu/blob/c07caa063a0c070759863d41ecb6094271417ae2/xemu/z80ex/orig-dist-files/examples/dasm.c#L32-L41

https://github.com/lgblgblgb/xemu/blob/c07caa063a0c070759863d41ecb6094271417ae2/xemu/z80ex/orig-dist-files/examples/dasm.c#L58-L61
**Used version of the project**
All

**To Reproduce**
NO

**Expected behavior**
Minor

**Comment by lgblgblgb** [comment]
Hi! Thanks for reporting a bug. However that directory there `z80ex/orig-dist-files` is not used for anything as an actual code in Xemu. It's just meant to be a directory some can look up what z80ex was shipped originally with, what I _don't_ use in Xemu though. It's just for reference, and should be the original distribution files with the version of z80ex, my modified work is based on.

**Comment by ryancaicse** [comment]
@lgblgblgb OK. Thank you for your reply.

**Comment by lgblgblgb** [comment]
Thanks for the feedback and understanding.
