### ISSUE TITLE
MEGA65: trace continue (t0) crashes xemu

### ISSUE THREAD

**Issue by ki-bo** [lgblgblgb/xemu#333]
Xemu crashes when using t0 command in uartmon

Found in next branch

**To Reproduce**
1. Start Xemu with uartmon (I used unix domain sockets on macOS)
2. Enter trace mode with t1
3. Exit trace mode with t0
Xemu crashes

**Comment by lgblgblgb** [comment]
Please command at #335

**Comment by lgblgblgb** [comment]
Closing this, moved to #335
