### ISSUE TITLE
MEGA65: VIC-II bank ignored when displaying sprites in VIC-IV mode

### ISSUE THREAD

**Issue by dillof** [lgblgblgb/xemu#342]
**Describe the bug**
The VIC-II bank is set to $8000 via CIA2_PRA, VIC hot registers disabled, charset, screen position, and sprite pointer set via VIC-IV registers. 

On MEGA65, the correct sprites are displayed, on xmega65 the data from bank 0 is displayed instead.

**Used version of the project**
```
**** The Evolving MEGA65 emulator from LGB ****
This software is part of the Xemu project: https://github.com/lgblgblgb/xemu
CREATED: travis@lgb on Darwin 18.7.0 at Tue Apr 26 10:24:46 GMT 2022
CREATED: clang 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8) 64LE for osx
VERSION: https://github.com/lgblgblgb/xemu.git master 08ed0450f53a65a285dcac802373aea4f9c6450d 20220426121838 official-build
EMULATE: MEGA65 (mega65): xmega65 (../../build/bin/xmega65.native) for mega65 on osx (native) using cc
```

**To Reproduce**
Start the attached program on the emulator.

[anykey-mega65.prg.zip](https://github.com/lgblgblgb/xemu/files/8731997/anykey-mega65.prg.zip)

Sources are at [GitHub](https://github.com/T-Pau/Anykey). (For the build above, I've commented out line 135 of start-vicii.s that copies the sprite data to bank 0 as a workaround for this bug.)

If it helps, I can try to create a smaller example program.

**Expected behavior**
In the lower right corner, a logo should be displayed.

**Screenshots**

How it looks in the emulator:
<img width="697" alt="Screenshot 2022-05-19 at 18 07 17" src="https://user-images.githubusercontent.com/1974387/169347027-50cc5cf1-fce3-450c-b3ea-11eb6cefd92f.png">

How it looks on the MEGA65:
<img width="692" alt="Screenshot 2022-05-19 at 18 07 35" src="https://user-images.githubusercontent.com/1974387/169347030-deff4c6a-327a-4a36-b4be-c7f95db33c49.png">

**Computer/Device (please complete the following information):**
 - Device/Platform: Mac
 - OS and its version: macOS 12.3.1

**Additional context**

**Comment by lgblgblgb** [comment]
@hernandp Any chance you to want this? :) If no, I would queue it for myself after my ongoing things sorted out a bit.

**Comment by hernandp** [comment]
Sure , I will handle it

**Comment by hernandp** [comment]
@dillof Looking at your code, it is possible that for the MEGA65 case you are *not touching any of the $DD00* registers?

```.macro set_vic_bank base_address
.if .not .defined(__MEGA65__)
    lda CIA2_PRA ; switch VIC bank
    and #$fc
    ora #((base_address >> 14) ^ 3)
    sta CIA2_PRA
.endif
.endmacro
```

Because I wrote some other test programs and I'm a bit puzzled on how banking scheme is behaving with MEGA65 mode.

**Comment by hernandp** [comment]
Fixed.  Now I understand:  bank is fetch always from bits 14 and 15 and this may be set by $D06C-$D06E or $DD00 if Hotregs are enabled.  Sounds much better.

![image](https://user-images.githubusercontent.com/4740613/187336826-4c943eba-92f8-4225-9089-38a7ea25c082.png)

**Comment by hernandp** [comment]
https://github.com/lgblgblgb/xemu/pull/355

**Comment by lgblgblgb** [comment]
@hernandp Closing this now. If you have objection not to do that _yet_, please tell ;)
