### ISSUE TITLE
MEGA65: Top border does not cover chars, when TEXTYPOS ($D04E) has lower value than top border register AND using GotoX instruction

### ISSUE THREAD

**Issue by ghost** [lgblgblgb/xemu#353]
Chars are not displayed behind the border as on hardware, when shifting screen up by decrementing TEXTYPOS ($d04e).
This only applies to the top border.

using version: Xemu/MEGA65 20220613133247

Regarding this image, the part above the colored raster lines should be covered by the border.
![TEXTYPOS_D04E](https://user-images.githubusercontent.com/109253283/178883466-569ada05-e7d6-44de-bcd8-15a0667c2323.png)

**Comment by lgblgblgb** [comment]
@hernandp Do you have willpower to take care this one?

**Comment by hernandp** [comment]
Sure sir!  I will handle it.  Thanks @lgblgblgb

**Comment by hernandp** [comment]
@xhl77  Do you have any minimal sample code?  I played with $D04E and $D048 registers and border seems to cover character generator accordingly.  Thanks.

**Comment by hernandp** [comment]
I have been playing with e.g: booting the machine,  
POKE $d048,104
POKE $d04e,100
and besides minimal subpixel differences in screen,  it's behaving properly.

Do you have any sample code @xhl77 ?   Do you think other registers are involved to cause the issue? Thanks.

**Comment by xhl77** [comment]
@hernandp I took a closer look at it, and I suspect gotox is causing problems. without there is no border issue.

Here are source code and prg files
[gotoX-border.zip](https://github.com/lgblgblgb/xemu/files/9146808/gotoX-border.zip)

hope this helps in some way.

**Comment by hernandp** [comment]
Thank you @xhl77 .  I will check your file, sorry for the late reply.

**Comment by lgblgblgb** [comment]
My comment (for myself not to forget later): https://github.com/lgblgblgb/xemu/pull/412#issuecomment-2351478962
