### ISSUE TITLE
MEGA65: $d06f.7 (PAL/NTSC) flag is always 0 when launching with autoload

### ISSUE THREAD

**Issue by RetroCogs** [lgblgblgb/xemu#357]
**Describe the bug**
When launching Xemu with -autoload command the PAL/NTSC flag in $d06f.7 is always showing as 0.

**Used version of the project**
![image](https://user-images.githubusercontent.com/45956643/190007312-fd04238c-0ad8-4c5e-9392-3f4bcb0a5177.png)

**To Reproduce**
launch Xemu and autoload a disk image

1. & 'C:\Program Files\xemu\xmega65.exe' -besure -autoload -8 "FShot.d81" -uartmon :4510
2. if you ?peek($d06f) it should show 0 for PAL and 128 for NTSC

**Expected behavior**
Reading from $d06f.7 should properly show which video standard you are using.

**Screenshots**
![image](https://user-images.githubusercontent.com/45956643/190006915-e873dd30-7d32-4007-8c2d-f83080bc229a.png)
![image](https://user-images.githubusercontent.com/45956643/190006993-6f376da5-a81f-4628-b617-8d1562825076.png)

**Computer/Device (please complete the following information):**
 - Device/Platform: PC
 - OS and its version: Windows 10 64 bit

**Comment by lgblgblgb** [comment]
@cbrsoft Thanks for the report, I'll look for this, cannot tell when exactly though as usual :-/

**Comment by lgblgblgb** [comment]
This is kinda mystical. I checked out exactly that version you mention above, and it works for me, even with the exact say command line options. Obviously I created a .d81 with that name with a small BASIC program what I autoload then:

![xemu](https://user-images.githubusercontent.com/884916/190226658-d5dd9521-0ad9-44a2-9824-54eb3f6ddca7.png)

When RUN it (or the mentioned command line to autoload it) I correctly got `0` then `128` then `0` as result, also the title bar of the emulator window changes (it has a delay of 1 sec to update the title bar, that's normal, it's for fighting the to rapid window events which would cause problems)

**Comment by lgblgblgb** [comment]
@RetroCogs I'm closing this, since no response, and I cannot reproduce the problem. Surely, just re-open, if you have anything to say!
