### ISSUE TITLE
MEGA65: Support for RRB reverse Y-row adjust

### ISSUE THREAD

**Issue by RetroCogs** [lgblgblgb/xemu#400]
New feature for RRB was added with this update https://github.com/MEGA65/mega65-core/issues/796.

This Issue is used for tracking updating Xemu to match support level.

Mega65 Issue 796 adds the support for indicating that FCM data Y offset should be subtracted instead of added, this fixes the issue that with parallax scrolling you'd need to duplicate your map char data. It also makes RRB sprites easier to implement.

I've validated that FShot (maybe the most extensive use of RRB) and my new sample to test this new feature both work flawlessly.

**Comment by lgblgblgb** [comment]
@RetroCogs Merged into `next`. Again, thanks for your contribution!
