### ISSUE TITLE
MEGA65: VIC-IV RRB transparency issue

### ISSUE THREAD

**Issue by RetroCogs** [lgblgblgb/xemu#407]
**Describe the bug**
When using RRB and setting transparency using GOTOX, once transparency is set it cannot be unset for that line.

**Used version of the project**
Observed on version 20240620201019 next

**To Reproduce**
Using RRB, set transparency using color ram byte 0-bit7 and draw a character, then clear transparency using color ram byte 0-bit7.

You will notice that the following RRB chars are still transparent.

**Expected behavior**
Setting / clearing color ram byte0-bit7 when GOTOX is set should correctly switch between transparent and opaque.

**Screenshots**
Showing the sample program on Emu showing the issue.

![image](https://github.com/user-attachments/assets/9c1a6bc6-f3e4-4273-9710-a731c858dcc3)

Showing the sample program on HW with correct behavior.

<img width="464" alt="image" src="https://github.com/user-attachments/assets/5dd3e3b6-6d5b-46b2-af19-a38fc854938c">

**Computer/Device (please complete the following information):**
 - Mac
 - Sonoma 14.6.1

**Additional context**

**Comment by lgblgblgb** [comment]
As I've written on Discord: Great, thanks! As far as I can see, this is a kind of problem we had before; only setting/resetting a thing on GOTOX token but missing the "else" branch for the opposite.

**Comment by lgblgblgb** [comment]
@RetroCogs I cannot test this patch too much right now, but judging by the diff, it's quite trivial to understand what it does and how, so I think it's safe to be merged by me right now. Thanks again.
