### ISSUE TITLE
MEGA65: Writing to $777xxxx from m65dbg does not work

### ISSUE THREAD

**Issue by johansmolinski** [lgblgblgb/xemu#411]
**Describe the bug**
xmega65 seems to have an issue when using m65dbg to write to memory in the CPU context using 777 prefix. Reading works fine though.

```
mbp:~ johan$ m65dbg -l tcp
m65dbg - v1.00
======
localhost resolved to 127.0.0.1
Xemu detected!
- Type 'help' for new commands, '?'/'h' for raw commands.
<dbg>mffd3020
:FFD3020:06060102030102010102030405060753
<dbg>m777d020
:000D020:06060102030102010102030405060753
<dbg>s777d020 00
<dbg>mffd3020
:FFD3020:06060102030102010102030405060753
<dbg>m777d020
:000D020:06060102030102010102030405060753
```

Expected result when running the m65dbg commands as above would be something like

```
<dbg>mffd3020
:FFD3020:00060102030102010102030405060753
<dbg>m777d020
:000D020:00060102030102010102030405060753
```

**Used version of the project**
```
mbp:~ johan$ xmega65 -h
**** The Evolving MEGA65 emulator from LGB ****
This software is part of the Xemu project: https://github.com/lgblgblgb/xemu
CREATED: johan@mbp.local on Darwin 23.4.0 at Tue Sep 10 13:40:58 CEST 2024
CREATED: clang Apple LLVM 15.0.0 (clang-1500.3.9.4) 64LE for osx
VERSION: git@github.com:lgblgblgb/xemu.git master 7a9e860ff5ce61dad53de5b9ca18b7100dd2bb8a 20240807161529 custom-build
```

**To Reproduce**
1. `xmega65 -fastboot -uartmon :4510 -testing`
2. `m65dbg -l tcp`
3. `<dbg>s777d020 00`
4. `<dbg>m777d020`
...

**Expected behavior**
Verify the first byte is indeed 00 (which it will not be, because of the bug)

**Computer/Device (please complete the following information):**
 - Device/Platform: MacBook Pro M1 Max
 - OS and its version: Sonoma 14.4.1
 - m65dbg version: v1.00

**Comment by lgblgblgb** [comment]
Thanks for the contribution to the project in the form of a bug report! Indeed, it's a problem, fortunately relatively easy to fix: the handler code in Xemu for the 's' command simply does not even checked the '0x777' and always did a linear write. Unlike memory reading, where it's handled. I guess it was simply forgotten by me to do so on the write case when I wrote this code ... Fix will be released to branch `next` soon.

**Comment by johansmolinski** [comment]
It seems to be a similar issue with `mpoke`, but maybe they are internally the same thing?

**Comment by lgblgblgb** [comment]
> It seems to be a similar issue with `mpoke`, but maybe they are internally the same thing?

`mpoke` is not really a protocol level command, it's an m65dbg "local" extension, m65dbg processes that as its own but then it sends `s` command to MEGA65/Xemu anyway at the end. So by fixing the `s` command on Xemu side, all m65dbg stuff using that command should work.

m65dbg utility is a bit tricky, since some features are not actual protocol level features, MEGA65 or Xemu would understand, but it has its own "local" processing as well for having some more nice "higher level" commands for the user. I have to admit, I had no idea what `mpoke` is, just now checked the source code of `m65dbg` ;) I knew, there are local stuffs like this, but I was not aware of `mpoke` before.

**Comment by lgblgblgb** [comment]
@johansmolinski Closing now, as the fix has been committed to the `next` branch (the usual approach: the `master` aka "stable" branch has been updated from `next` if enough changes accumulated in `next`, so it's not instant).

Pls comment or re-open **if** you find anything problematic with this fix.
