### ISSUE TITLE
MEGA65: vic4 is only reading ChrCount from $d05e and is ignoring remaining 2 bits in $d063

### ISSUE THREAD

**Issue by RetroCogs** [lgblgblgb/xemu#416]
**Describe the bug**
Title pretty much says it all, ChrCount is a 10 bit number using $d05e as LSB and $d063.4&5 as MSB.

e.g. In Xemu, if ChrCount is set to 266 it will only render 10 chars ...

**Comment by lgblgblgb** [comment]
@RetroCogs Thank you very much for the fix and PR! I have some comments on it though if you don't mind, please see: https://github.com/lgblgblgb/xemu/pull/417
