### ISSUE TITLE
Compiling the Mega65 target on linux 

### ISSUE THREAD

**Issue by sausagejohnson** [lgblgblgb/xemu#63]
build-essential is already the newest version.                                                                                                            
libreadline-dev is already the newest version.                                                                                                            
git is already the newest version.                                                                                                                        
libgtk-3-dev is already the newest version.
libsdl2-dev is already the newest version.
(according to Ubuntu 14.04.3 LTS)

gcc version is 6.4.0. Compiling the C65 target compiles fine. Result of 'make' is:

gcc -std=gnu11 -Ofast -fno-common -falign-functions=16 -falign-loops=16 -ffast-math -Wall -pipe -I/usr/local/include/SDL2 -D_REENTRANT -D HAVE_SDL2 -D HAVE_SOCKET_OS_API -I. -I../.. -include xemu/arch-sys-native.h -c -o ../../build/objs/c-native-mega65-xmega65--ethertap.o ../../xemu/ethertap.c
In file included from ../../xemu/ethertap.c:69:0:
/usr/include/linux/if.h:143:8: error: redefinition of ‘struct ifmap’
 struct ifmap {
        ^~~~~
In file included from ../../xemu/ethertap.c:68:0:
/usr/include/net/if.h:111:8: note: originally defined here
 struct ifmap
        ^~~~~
In file included from ../../xemu/ethertap.c:69:0:
/usr/include/linux/if.h:177:8: error: redefinition of ‘struct ifreq’
 struct ifreq {
        ^~~~~
In file included from ../../xemu/ethertap.c:68:0:
/usr/include/net/if.h:126:8: note: originally defined here
 struct ifreq
        ^~~~~
In file included from ../../xemu/ethertap.c:69:0:
/usr/include/linux/if.h:226:8: error: redefinition of ‘struct ifconf’
 struct ifconf  {
        ^~~~~~
In file included from ../../xemu/ethertap.c:68:0:
/usr/include/net/if.h:176:8: note: originally defined here
 struct ifconf
        ^~~~~~

**Comment by sausagejohnson** [comment]
Decided to see if I could work it out. Fixed with the following PR: https://github.com/lgblgblgb/xemu/pull/64

But that may not suit all gcc library setups.

**Comment by lgblgblgb** [comment]
Hmm, thanks, but Ubuntu 14 is kinda old, just some months and support is over, if I am correct. I guess, I haven't noticed any problem (built with Travis at every commit automatically), because really I haven't tried to compile it on anything "that old". I wasn't even aware that 14.04 has SDL 2.0.4 already (maybe in backports?). Anyway, it can't hurt for sure, to accept that PR if it doesn't break anything other ... I'll check it, thanks again.

**Comment by sausagejohnson** [comment]
Thanks lgblgblgb. I might have picked up SDL 2.0.4 from elsewhere and have a somewhat hybrid distro now. But yes please, test first, as I haven't checked it anywhere else.

If it becomes a case of a minimum version of Ubuntu required, it would be good to document this in the readme and main repo wiki.

**Comment by sausagejohnson** [comment]
Oh right, yes I made the change against master. I'll close and reopen against dev if you prefer.

**Comment by lgblgblgb** [comment]
I've merged that change, thanks. About the issue on "minimal requirements", it's really hard to say, unless test is done throughout dozens of different popular distros at least with all (at least) the still supported versions. But it's always welcome if someone can test one thing at least (like you) and can find some problem, and it's even more welcome if the solution is there too :)
