### ISSUE TITLE
MacOS Platform: DMG file, app-bundle, the "plist" file, etc ...

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#84]
For easier life of OSX users, please find a way to create easy-to-use "installer" (maybe dmg file?). It should be an automated process can be done by command line tools, automatically on build systems (like Travis, or Github Actions), not a GUI based solution, made by "hand".

**Comment by lgblgblgb** [comment]
In commit b381dc4564457e4b9f0c9597c3495b493cfa08c0 I try to create a DMG on Travis CI OSX build with the "create-dmg" utility (see: homebrew), see: https://github.com/andreyvit/create-dmg

Still, i guess it is VERY far from being nice ...

**Comment by lgblgblgb** [comment]
The actual part which is slow on travis using the mentioned create-dmg:

    Creating disk image...
    created: /Users/travis/build/lgblgblgb/xemu/rw.Xemu-Installer.dmg
    Mounting disk image...
    Unmounting disk image...
    Mount directory: /Volumes/Xemu Installer
    Device name:     /dev/disk2
    making link to Applications dir
    /Volumes/Xemu Installer
    Copying volume icon file 'build/xemu.icns'...
    Running Applescript: /usr/bin/osascript "/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/createdmg.tmp.XXXXXXXXXX.e1LHQhEJ" "Xemu Installer"
    /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn /T/createdmg.tmp.XXXXXXXXXX.e1LHQhEJ:396:408: execution error: Finder got an error:   AppleEvent timed out. (-1712)
    Done running the applescript...
    Fixing permissions...

See the problem at "AppleEvent timed out" before it shows up, **MINUTES** passes ...

Also the DMG structure is a problem, no icon (just the "exec") for Xemu binaries, and MacOS opens a terminal as well for some reason if binary is started. Probably other issues as well ...

**Comment by lgblgblgb** [comment]
My work what I did in the risky-disky branch: https://github.com/lgblgblgb/xemu/blob/risky-disky/build/dmg-osx-creator.sh

In theory it "should" have some "nice looking" apps at least but as Martin tested, it seems emulators can be run: BUT then Xemu complains it got an unknown parameter somehow :-O

<img width="532" alt="imgpsh_fullsize_anim" src="https://user-images.githubusercontent.com/884916/74269168-60111c80-4d09-11ea-83e7-4376f22ce746.png">

Surely it's not the whole story, see above, and the stuff as well with create-dmg waits a LOT for some thing to time out (?).

**Comment by hernandp** [comment]
I can handle polishing this up.

**Comment by lgblgblgb** [comment]
https://www.google.com/search?q=macos+%22-psn%22+parameter&ie=utf-8&oe=utf-8

Just found. So it seems, really it's a macOS feature to pass some -psn... parameter to any app started by finder :-D Wow, that's strange :-O Now the question it can be eliminated with some info.plist parameter I write now as will in that script, or no way to do anything, and the main Xemu command line parser should be patched to simply ignore these :-O This is now a real madness what MacOS does from time to time, better say, almost always :-O

**Comment by lgblgblgb** [comment]
Patched against that behaviour: commit ec0ff9101a69f9a5834d7d7d173501458770d84a

**Comment by hernandp** [comment]
> Patched against that behaviour: commit [ec0ff91](https://github.com/lgblgblgb/xemu/commit/ec0ff9101a69f9a5834d7d7d173501458770d84a)

Nice catch!

**Comment by hernandp** [comment]
**Building under 15.10 (Catalina)**

NOTE:  create-dmg  stable from Homebrew is 1.0.0.5 which  fails because does not support macOS Catalina (the internet-enable option was removed from hdiutil which is called by create-dmg).

See https://github.com/andreyvit/create-dmg/releases/tag/v1.0.0.7

**Comment by lgblgblgb** [comment]
Yeah, it's possible! However as far as I see, Travis uses an older MacOS where I build Xemu, so at least there it's not a problem. I'm not aware what "internet-enable" means at all :-O Do we need it? Since it seems, create-dmg has an option to skip that step, just I'm not sure, what is this "internet-enable" stuff at all :-O

**Comment by lgblgblgb** [comment]
Btw about the long wait and timeout, I found an issue on `create-dmg` what I also commented now:

https://github.com/andreyvit/create-dmg/issues/72

**Comment by lgblgblgb** [comment]
Can we do something more here? No idea about that timeout :( The best I could found to use an undocumented `--skip-jenkins` or whatever cli switch to create-dmg which skips that part. Though it's said then it will skip some steps on DMG formatting or whatever :-O Btw I found that switch on the issue of the create-dmg project I've posted above.
