### ISSUE TITLE
Windows Platform: review, enhance installer of Xemu on Windows

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#93]
Test, review, and maybe fix/enhance of the NSI installer of Xemu on Windows. Also, if possible it should work on Linux to BUILD it (now I use wine to execute make NSI ... there is also native Linux version of NSI maker, but DIFFERENT version where the nsi descriptor file of Xemu cannot be understood ...).

**Comment by lgblgblgb** [comment]
Commit b381dc4564457e4b9f0c9597c3495b493cfa08c0 does slight rework of NSI, using native makensis utility (native to Linux) instead of a Windows based one running with Wine on Linux :-O

**Comment by hernandp** [comment]
I reviewed the installer and uninstaller and I think they are quite good.  Icons are placed properly in the Start Menu and Uninstaller works.

**Comment by lgblgblgb** [comment]
Well, if you can't find any major problem, I can close this, I guess. For sure, as usual, in case of any "minor" problem other than "major"/"conceptional", there can be new specific issue in the future.
